# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ffmFBENKQ7z5nLZyNWfFxDMwTPAlbaE
"""

# prompt: write a code on sentiment analysis on twitter

!pip install tweepy textblob

import tweepy
from textblob import TextBlob

# Your Twitter API credentials
consumer_key = "YOUR_CONSUMER_KEY"
consumer_secret = "YOUR_CONSUMER_SECRET"
access_token = "YOUR_ACCESS_TOKEN"
access_token_secret = "YOUR_ACCESS_TOKEN_SECRET"

# Authenticate with Twitter API
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

def analyze_sentiment(tweet):
    analysis = TextBlob(tweet)
    if analysis.sentiment.polarity > 0:
        return 'Positive'
    elif analysis.sentiment.polarity == 0:
        return 'Neutral'
    else:
        return 'Negative'

def analyze_tweets(query, num_tweets=100):
    tweets = tweepy.Cursor(api.search_tweets, q=query, lang="en").items(num_tweets)
    results = []
    for tweet in tweets:
        sentiment = analyze_sentiment(tweet.text)
        results.append({
            'tweet': tweet.text,
            'sentiment': sentiment
        })
    return results

if __name__ == "__main__":
    search_term = "your search term here" # Replace with the topic you want to analyze
    tweet_results = analyze_tweets(search_term)

    for tweet_data in tweet_results:
        print(f"Tweet: {tweet_data['tweet']}")
        print(f"Sentiment: {tweet_data['sentiment']}")
        print("---")

